### ISSUE TITLE
unable to apply cgroup configuration

### ISSUE THREAD

**Issue by R0CKB0TT0M** [dmpanch/hassio-rpi4-docker-compose#2]
I updated my system and containers yesterday and ever since hassio doesn't start anymore. I tried google but I couldn't find anything relevant so here I am. Other containers such as nextcloud are running fine.

My system:
Raspberrypi 4 4gb
OS: manjaro-arm for raspberrypi
Systemd 250
Docker version 20.10.12, build e91ed5707e

the error:
` docker-compose up -d
[+] Running 1/2
 ⠿ Container portainer          Running                                                                            0.0s
 ⠧ Container hassio_supervisor  Starting                                                                           0.7s
Error response from daemon: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: chown /sys/fs/cgroup/system.slice/docker-9b70865b8d8a2e4270437daed985be742914bbb5c9733189efdad361c44b1dc2.scope/memory.oom.group: no such file or directory: unknown`

It might just be that I'm being stupid. in that case sorry for wasting your time. let me know if you need anything else.

**Comment by dmpanch** [comment]
Seems like issue is not related to this project, please follow the[ issue in the docker repository](https://github.com/docker/for-linux/issues/841).
